name: Trigger GitLab CI from GitHub

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI
        run: |
          curl --request POST \
          --form token=glptt-ac3d4c5b9fc320233712050c15417ec45597cce7 \
          --form ref=main \
          https://gitlab.com/api/v4/projects/61872632/trigger/pipeline
